### ISSUE TITLE
Command line options or config options to start with borders

### ISSUE THREAD

**Issue by nunoh** [AnthonyDiGirolamo/todotxt-machine#25]
I would like to be able to start this with borders enabled already. From what I take from the README and the help flag that doesn't seem to be able to do. And the same goes for any UI option. Think that would add up a bit to the project. 

Kudos on the project. Pretty darn cool :bow:

**Comment by kespindler** [comment]
Hey @nunoh are you still interested in this feature? I have a fork at kespindler/todotxt-machine where I add a few command line options, although not what you're mentioning. Planning on some PRs to merge back to this project this weekend.

**Comment by nunoh** [comment]
I am not using `todotxt-machine` anymore myself. Still imagine that there could be some users around that would find that cool. Thanks for the follow up though. :smiley:

**Comment by kespindler** [comment]
Cool. Curious- what are you using instead?

**Comment by nunoh** [comment]
Well, I keep trying different stuff from time to time, cause I never seem to be 100% satisfied with what I am using. Although, what I've found that works the best for me so far is actually OmniFocus. A bit on the "dark side" I know, but seems to works the best for me really. Would like to write my own fully customized todo app one day though. Have a spec that I keep building on every week or so. :smile:

**Comment by nunoh** [comment]
Wow. Great :)
